# Create a Simple Calculator

import tkinter as tk

window = tk.Tk()
window.title("SIMPLE CALCULATOR")

button1 = tk.Button(window, text="1", bg="green")
button1.pack()
button1 = tk.Button(window, text="2", bg="green")
button1.pack()
button1 = tk.Button(window, text="3", bg="green")
button1.pack()
button1 = tk.Button(window, text="4", bg="green")
button1.pack()
button1 = tk.Button(window, text="5", bg="green")
button1.pack()
button1 = tk.Button(window, text="1", bg="green")
button1.pack()
button1 = tk.Button(window, text="6", bg="green")
button1.pack()
button1 = tk.Button(window, text="7", bg="green")
button1.pack()
button1 = tk.Button(window, text="8", bg="green")
button1.pack()
button1 = tk.Button(window, text="9", bg="green")
button1.pack()
button1 = tk.Button(window, text="0", bg="green")
button1.pack()
button1 = tk.Button(window, text="+", bg="green")
button1.pack()
button1 = tk.Button(window, text="-", bg="green")
button1.pack()
button1 = tk.Button(window, text="*", bg="green")
button1.pack()
button1 = tk.Button(window, text="/", bg="green")
button1.pack()


window.mainloop()
